const interests = [
    "Reading",
    "Writing",
    "Cooking",
    "Traveling",
    "Photography",
    "Gaming",
    "Drawing",
    "Painting",
    "Music",
    "Singing",
    "Dancing",
    "Watching Movies",
    "Cycling",
    "Hiking",
    "Running",
    "Yoga",
    "Meditation",
    "Fishing",
    "Gardening",
    "Swimming",
    "Fitness & Gym",
    "Martial Arts",
    "Playing Guitar",
    "Playing Piano",
    "Chess",
    "DIY Projects",
    "Blogging",
    "Podcasting",
    "Volunteering",
    "Collecting (Coins, Stamps, etc.)"
  ];
  
  module.exports = interests;
  